# [Conductor] Airtight Dockerfile for rfgo-embedding-worker
FROM harbor.foundrymtc.samsungds.net/library/python:3.13

ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY
ENV https_proxy=$HTTPS_PROXY

ENV PIP_TRUSTED_HOST=pypi.org pypi.python.org files.pythonhosted.org nexus.internal.com
ENV PYTHONHTTPSVERIFY=0

WORKDIR /app

RUN pip config set global.index-url https://nexus.internal.com/repository/pypi-all/simple

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Worker는 외부 포트 노출 없음
CMD ["python", "main.py"]
