apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfgo-web-nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfgo-web-nestjs
  template:
    metadata:
      labels:
        app: rfgo-web-nestjs
    spec:
      containers:
      - name: rfgo-web-nestjs
        image: harbor.internal/rfgo/rfgo-web-nestjs:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rfgo-web-nestjs
spec:
  selector:
    app: rfgo-web-nestjs
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
