"""auto_migration

Revision ID: c26f1ff371d0
Revises: 0e8510ccc89e
Create Date: 2026-03-20 10:45:50.994670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26f1ff371d0'
down_revision: Union[str, Sequence[str], None] = '0e8510ccc89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reticle_layouts')
    op.drop_index(op.f('_KeyDesignToProcessPlan_B_index'), table_name='_KeyDesignToProcessPlan')
    op.drop_table('_KeyDesignToProcessPlan')
    op.drop_table('request_assignees')
    op.drop_table('request_steps')
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('key_designs_name_key'), table_name='key_designs')
    op.drop_table('key_designs')
    op.drop_table('stream_info')
    op.drop_table('request_tables_map')
    op.alter_column('beol_options', 'option_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('beol_options', 'process_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('beol_options_process_plan_id_option_name_key'), table_name='beol_options')
    op.create_index(op.f('ix_beol_options_id'), 'beol_options', ['id'], unique=False)
    op.create_index(op.f('ix_beol_options_option_name'), 'beol_options', ['option_name'], unique=False)
    op.drop_constraint(op.f('beol_options_process_plan_id_fkey'), 'beol_options', type_='foreignkey')
    op.create_foreign_key(None, 'beol_options', 'process_plans', ['process_plan_id'], ['id'], ondelete='CASCADE')
    op.add_column('photo_keys', sa.Column('raw_binary', sa.LargeBinary(), nullable=True))
    op.alter_column('photo_keys', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photo_keys', 'rfg_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'photo_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'is_reference',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('photo_keys', 'table_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('photo_keys', 'rev_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photo_keys', 'workbook_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'updater',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'update_date',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_photo_keys_id'), 'photo_keys', ['id'], unique=False)
    op.drop_constraint(op.f('photo_keys_process_plan_id_fkey'), 'photo_keys', type_='foreignkey')
    op.drop_constraint(op.f('photo_keys_beol_option_id_fkey'), 'photo_keys', type_='foreignkey')
    op.drop_constraint(op.f('photo_keys_product_id_fkey'), 'photo_keys', type_='foreignkey')
    op.create_foreign_key(None, 'photo_keys', 'beol_options', ['beol_option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'photo_keys', 'process_plans', ['process_plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'photo_keys', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('process_plans', 'design_rule',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('process_plans_design_rule_key'), table_name='process_plans')
    op.create_index(op.f('ix_process_plans_design_rule'), 'process_plans', ['design_rule'], unique=True)
    op.create_index(op.f('ix_process_plans_id'), 'process_plans', ['id'], unique=False)
    op.alter_column('product_meta', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_meta', 'process_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('product_meta', 'customer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('product_meta', 'application',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('product_meta_product_id_key'), table_name='product_meta')
    op.create_index(op.f('ix_product_meta_id'), 'product_meta', ['id'], unique=False)
    op.create_unique_constraint(None, 'product_meta', ['product_id'])
    op.drop_constraint(op.f('product_meta_product_id_fkey'), 'product_meta', type_='foreignkey')
    op.create_foreign_key(None, 'product_meta', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_meta', 'update_time')
    op.drop_column('product_meta', 'created_at')
    op.alter_column('products', 'partid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('products', 'beol_option_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('products_partid_key'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_partid'), 'products', ['partid'], unique=True)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.drop_constraint(op.f('products_beol_option_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'beol_options', ['beol_option_id'], ['id'], ondelete='CASCADE')
    op.alter_column('request_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_items', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('request_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('request_items', 'edm_list',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('request_items', 'pkd_versions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('request_items', 'requester_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_request_items_id'), 'request_items', ['id'], unique=False)
    op.drop_constraint(op.f('request_items_product_id_fkey'), 'request_items', type_='foreignkey')
    op.create_foreign_key(None, 'request_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('request_items', 'request_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_items', sa.Column('request_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'request_items', type_='foreignkey')
    op.create_foreign_key(op.f('request_items_product_id_fkey'), 'request_items', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_request_items_id'), table_name='request_items')
    op.alter_column('request_items', 'requester_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('request_items', 'pkd_versions',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('request_items', 'edm_list',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('request_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('request_items', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('request_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_beol_option_id_fkey'), 'products', 'beol_options', ['beol_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_partid'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('products_partid_key'), 'products', ['partid'], unique=True)
    op.alter_column('products', 'beol_option_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'partid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('product_meta', sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('product_meta', sa.Column('update_time', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_meta', type_='foreignkey')
    op.create_foreign_key(op.f('product_meta_product_id_fkey'), 'product_meta', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'product_meta', type_='unique')
    op.drop_index(op.f('ix_product_meta_id'), table_name='product_meta')
    op.create_index(op.f('product_meta_product_id_key'), 'product_meta', ['product_id'], unique=True)
    op.alter_column('product_meta', 'application',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product_meta', 'customer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product_meta', 'process_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product_meta', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_process_plans_id'), table_name='process_plans')
    op.drop_index(op.f('ix_process_plans_design_rule'), table_name='process_plans')
    op.create_index(op.f('process_plans_design_rule_key'), 'process_plans', ['design_rule'], unique=True)
    op.alter_column('process_plans', 'design_rule',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'photo_keys', type_='foreignkey')
    op.drop_constraint(None, 'photo_keys', type_='foreignkey')
    op.drop_constraint(None, 'photo_keys', type_='foreignkey')
    op.create_foreign_key(op.f('photo_keys_product_id_fkey'), 'photo_keys', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('photo_keys_beol_option_id_fkey'), 'photo_keys', 'beol_options', ['beol_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('photo_keys_process_plan_id_fkey'), 'photo_keys', 'process_plans', ['process_plan_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_photo_keys_id'), table_name='photo_keys')
    op.alter_column('photo_keys', 'update_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('photo_keys', 'updater',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'workbook_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('photo_keys', 'rev_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photo_keys', 'table_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('photo_keys', 'is_reference',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('photo_keys', 'photo_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'rfg_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('photo_keys', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('photo_keys', 'raw_binary')
    op.drop_constraint(None, 'beol_options', type_='foreignkey')
    op.create_foreign_key(op.f('beol_options_process_plan_id_fkey'), 'beol_options', 'process_plans', ['process_plan_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_beol_options_option_name'), table_name='beol_options')
    op.drop_index(op.f('ix_beol_options_id'), table_name='beol_options')
    op.create_index(op.f('beol_options_process_plan_id_option_name_key'), 'beol_options', ['process_plan_id', 'option_name'], unique=True)
    op.alter_column('beol_options', 'process_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('beol_options', 'option_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('request_tables_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_key_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('beol_option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('process_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_key_id'], ['photo_keys.id'], name=op.f('request_tables_map_photo_key_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_items.id'], name=op.f('request_tables_map_request_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('request_tables_map_pkey'))
    )
    op.create_table('stream_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('process_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beol_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stream_input', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('stream_output', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request_items.id'], name=op.f('stream_info_request_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('stream_info_pkey'))
    )
    op.create_table('key_designs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('size_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_vertical', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_horizontal', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('rotation', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gds_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edm_list', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('x_axis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('y_axis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('key_designs_pkey'))
    )
    op.create_index(op.f('key_designs_name_key'), 'key_designs', ['name'], unique=True)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('request_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'TODO'::text"), autoincrement=False, nullable=False),
    sa.Column('work_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_items.id'], name=op.f('request_steps_request_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('request_steps_pkey'))
    )
    op.create_table('request_assignees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request_items.id'], name=op.f('request_assignees_request_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('request_assignees_pkey'))
    )
    op.create_table('_KeyDesignToProcessPlan',
    sa.Column('A', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('B', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['A'], ['key_designs.id'], name=op.f('_KeyDesignToProcessPlan_A_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['process_plans.id'], name=op.f('_KeyDesignToProcessPlan_B_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('A', 'B', name=op.f('_KeyDesignToProcessPlan_AB_pkey'))
    )
    op.create_index(op.f('_KeyDesignToProcessPlan_B_index'), '_KeyDesignToProcessPlan', ['B'], unique=False)
    op.create_table('reticle_layouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beol_option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('process_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shot_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chips', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scribelanes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('placements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('reticle_layouts_product_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reticle_layouts_pkey'))
    )
    # ### end Alembic commands ###
