{{- if and .Values.externalDatabase.enabled .Values.externalDatabase.secretData -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDatabase.secretName }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.externalDatabase.secretData.dbUser | quote }}
  DB_PASSWORD: {{ .Values.externalDatabase.secretData.dbPassword | quote }}
{{- end }}
