apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nameOverride | default .Release.Name }}
