apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rfgo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moyuchan84/rf.git
    targetRevision: HEAD
    path: rfgo-deploy/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rfgo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
