apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rfgo-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: rfgo-dev
          - env: prod
            namespace: rfgo-prod
  template:
    metadata:
      name: 'rfgo-{{env}}'
    spec:
      project: rfgo-project
      sources:
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-service'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/react.yaml'
              - '../../values/services/{{env}}/react.yaml'
            values: |
              nameOverride: react
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-service'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/nestjs.yaml'
              - '../../values/services/{{env}}/nestjs.yaml'
            values: |
              nameOverride: nestjs
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-service'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/fastapi.yaml'
              - '../../values/services/{{env}}/fastapi.yaml'
            values: |
              nameOverride: fastapi
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-service'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/rag.yaml'
              - '../../values/services/{{env}}/rag.yaml'
            values: |
              nameOverride: rag
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-service'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/embedding.yaml'
              - '../../values/services/{{env}}/embedding.yaml'
            values: |
              nameOverride: embedding
        - repoURL: 'https://github.com/moyuchan84/rf.git'
          targetRevision: main
          path: 'charts/rfgo-redis'
          helm:
            valueFiles:
              - '../../values/env/{{env}}.yaml'
              - '../../values/services/common/redis.yaml'
              - '../../values/services/{{env}}/redis.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
