"""Initial tables

Revision ID: 03c8e740f2c7
Revises: 
Create Date: 2026-03-15 14:14:34.621360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c8e740f2c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_rule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_plans_design_rule'), 'process_plans', ['design_rule'], unique=True)
    op.create_index(op.f('ix_process_plans_id'), 'process_plans', ['id'], unique=False)
    op.create_table('beol_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.Column('process_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_plan_id'], ['process_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beol_options_id'), 'beol_options', ['id'], unique=False)
    op.create_index(op.f('ix_beol_options_option_name'), 'beol_options', ['option_name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partid', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('beol_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beol_option_id'], ['beol_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_partid'), 'products', ['partid'], unique=True)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('photo_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('rfg_category', sa.String(), nullable=True),
    sa.Column('photo_category', sa.String(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('rev_no', sa.Integer(), nullable=True),
    sa.Column('workbook_data', sa.JSON(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('updater', sa.String(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_keys_id'), 'photo_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_keys_id'), table_name='photo_keys')
    op.drop_table('photo_keys')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_partid'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_beol_options_option_name'), table_name='beol_options')
    op.drop_index(op.f('ix_beol_options_id'), table_name='beol_options')
    op.drop_table('beol_options')
    op.drop_index(op.f('ix_process_plans_id'), table_name='process_plans')
    op.drop_index(op.f('ix_process_plans_design_rule'), table_name='process_plans')
    op.drop_table('process_plans')
    # ### end Alembic commands ###
